[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "XAI-metrics"
version = "0.1.0"
description = "Explainability metrics library"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "numpy",
  "pandas",
  "torch",
  "quantus",
  "cloudpickle",
  "matplotlib",
  "seaborn",
  "scikit-learn",
  "pyod",
  "shap",
  "lime",
  "interpret",
  "pyyaml>=6.0.3",
  "pytest>=9.0.3",
  "aix360>=0.3.0",
  "dalex>=1.8.0",
  "sphinx>=8.1.3",
  "sphinx-rtd-theme>=3.1.0",
  "joblib>=1.5.3",
]
license = { text = "MIT" }
authors = [
  { name = "Maria Teresa Alba Rueda", email = "maytalbada@gmail.com" }
]
keywords = ["XAI","metrics","explainability"]
classifiers = [
  "Programming Language :: Python",
  "Topic :: Scientific/Engineering :: Artificial Intelligence",
  "License :: OSI Approved :: MIT License"
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["xai_metrics*"]
