# xai_metrics/explainers/lime.py
import numpy as np
import pandas as pd
from lime.lime_tabular import LimeTabularExplainer
from torch import Tensor

from xai_metrics.base import BaseExplainer, register_explainer, ExplainerContext

from typing import Any, Mapping, Callable

@register_explainer
class LIMEExplainer(BaseExplainer):
    """
    LIME tabular explainer.

    This explainer computes local feature attributions using
    :class:`lime.lime_tabular.LimeTabularExplainer`. For each observation, LIME
    builds a local surrogate model around the input and returns feature weights
    for the selected target label.

    The returned attributions are arranged as a fixed-size matrix whose columns
    follow the order of ``context.X_background``. The explainer supports
    classification and regression models through ``predict_proba`` or
    ``predict``, respectively.

    The explainer is registered under the name ``"LIME"``.
    """
    NAME = "LIME"

    def __init__(
        self,
        context: ExplainerContext,
        params: Mapping[str, Any] | None = None
    ):
        """
        Parameters
        ----------
        context : ExplainerContext
            Shared explainer context. It must contain ``X_background`` and may
            contain ``y_background``. The background data are used to initialise
            the LIME tabular explainer, and their columns define the order of
            the returned attribution vectors.
        params : Mapping[str, Any] or None, optional
            Explainer-specific parameters. Supported keys are:

            - ``mode`` : str, optional
              LIME mode. Usually ``"classification"`` or ``"regression"``.
              The default value is ``"classification"``.

            - ``categorical_features`` : list or None, optional
              Indices of categorical features passed to LIME.

            - ``categorical_names`` : dict or None, optional
              Mapping from categorical feature indices to category names.

            - ``kernel_width`` : float or None, optional
              Width of the LIME kernel.

            - ``kernel`` : callable or None, optional
              Custom kernel function used by LIME.

            - ``verbose`` : bool, optional
              Whether LIME should print additional information. The default
              value is ``False``.

            - ``class_names`` : list or None, optional
              Class names used by LIME in classification mode.

            - ``feature_selection`` : str, optional
              Feature selection strategy used by LIME. The default value is
              ``"auto"``.

            - ``discretize_continuous`` : bool, optional
              Whether continuous features should be discretised. The default
              value is ``True``.

            - ``discretizer`` : str, optional
              Discretisation strategy used by LIME. The default value is
              ``"quartile"``.

            - ``sample_around_instance`` : bool, optional
              Whether perturbations should be sampled around the explained
              instance. The default value is ``False``.

            - ``random_state`` : int, optional
              Random state used by LIME. The default value is ``42``.

            - ``labels`` : tuple, list or None, optional
              Labels to explain. If not provided, the target labels passed to
              :meth:`explain` are used. If no targets are provided, label ``1``
              is used.

            - ``top_labels`` : int or None, optional
              Number of top labels to explain. When provided, the first label
              returned by LIME is used to build the attribution vector.

            - ``num_features`` : int, optional
              Maximum number of features included in each local explanation.
              The default value is the number of input features.

            - ``num_samples`` : int, optional
              Number of perturbed samples generated by LIME. The default value
              is ``500``.

            - ``distance_metric`` : str, optional
              Distance metric used by LIME. The default value is
              ``"euclidean"``.

            - ``model_regressor`` : Any or None, optional
              Regressor used by LIME to fit the local surrogate model.

            If ``None``, an empty dictionary is used.
        """
        super().__init__(context, params)

        self.cols = list(context.X_background.columns)

        self.explainer = LimeTabularExplainer(
            training_data=context.X_background.to_numpy(),
            mode=self.params.get("mode", "classification"),
            training_labels=None if context.y_background is None else context.y_background.to_numpy(),
            feature_names=self.cols,
            categorical_features=self.params.get("categorical_features"),
            categorical_names=self.params.get("categorical_names"),
            kernel_width=self.params.get("kernel_width"),
            kernel=self.params.get("kernel"),
            verbose=self.params.get("verbose", False),
            class_names=self.params.get("class_names"),
            feature_selection=self.params.get("feature_selection", "auto"),
            discretize_continuous=self.params.get("discretize_continuous", True),
            discretizer=self.params.get("discretizer", "quartile"),
            sample_around_instance=self.params.get("sample_around_instance", False),
            random_state=self.params.get("random_state", 42)
        )


    def _to_numpy(self, inputs: Any) -> np.ndarray:
        """
        Convert input data to a NumPy array.

        Parameters
        ----------
        inputs : Any
            Input observation or batch of observations. Supported inputs include
            pandas dataframes, torch tensors and array-like objects.

        Returns
        -------
        numpy.ndarray
            Two-dimensional array with one row per observation and columns in
            the same order as ``context.X_background``.
        """
        if isinstance(inputs, pd.DataFrame):
            values = inputs.loc[:, self.cols].to_numpy()
        elif isinstance(inputs, Tensor):
            values = inputs.detach().cpu().numpy()
        else:
            values = np.asarray(inputs)

        if values.ndim == 1:
            values = values.reshape(1, -1)

        return values
    
    
    def _get_predict_fn(self, model: Any, predict_fn: Callable | None = None) -> Callable:
        """
        Resolve the prediction function used by LIME.

        If ``predict_fn`` is provided, it is returned directly. Otherwise, the
        method searches for ``predict_proba`` in classification mode and
        ``predict`` in any other mode. The method is searched first on the model
        itself and then on ``model.model``.

        Parameters
        ----------
        model : Any
            Model to explain.
        predict_fn : Callable or None, optional
            Custom prediction function. If provided, it is used directly.

        Returns
        -------
        Callable
            Prediction function compatible with LIME.

        Raises
        ------
        AttributeError
            If the required prediction method is not available on ``model`` or
            ``model.model``.
        """
        if predict_fn is not None:
            return predict_fn

        mode = self.params.get("mode", "classification")

        if mode == "classification":
            method_name = "predict_proba"
        else:
            method_name = "predict"

        if hasattr(model, method_name):
            return getattr(model, method_name)

        if hasattr(model, "model") and hasattr(model.model, method_name):
            return getattr(model.model, method_name)

        raise AttributeError(
            f"No se encontro {method_name} en {type(model)} ni en model.model"
        )

    
    def explain(
        self,
        model: Any,
        inputs: Any,
        targets: Any | None = None,
        **kwargs: Any
    ) -> np.ndarray:
        """
        Generate LIME attributions for the provided inputs.

        The method converts the inputs to a NumPy array, resolves the prediction
        function and computes one LIME explanation per observation. The selected
        LIME weights are converted into attribution vectors ordered according
        to ``context.X_background``.

        If ``labels`` and ``top_labels`` are not configured, the method uses the
        provided ``targets`` as labels. If no targets are provided, label ``1``
        is explained by default.

        Parameters
        ----------
        model : Any
            Model whose predictions are to be explained.
        inputs : Any
            Input observation or batch of observations to explain.
        targets : Any or None, optional
            Target labels to explain when ``labels`` and ``top_labels`` are not
            provided in ``params``.
        **kwargs : Any
            Additional keyword arguments. They are accepted for compatibility
            with the common explainer interface.

        Returns
        -------
        numpy.ndarray
            Attribution matrix with one row per explained observation and one
            column per feature.
        """
        X_np = self._to_numpy(inputs)
        predict_fn = self._get_predict_fn(model)

        labels = self.params.get("labels", None)
        top_labels = self.params.get("top_labels", None)
        num_features = self.params.get("num_features", len(self.cols))
        num_samples = self.params.get("num_samples", 500)
        distance_metric = self.params.get("distance_metric", "euclidean")
        model_regressor = self.params.get("model_regressor", None)

        attributions = []
        
        for i, row in enumerate(X_np):
            if labels is None and top_labels is None:
                if targets is not None:
                    target = int(np.asarray(targets).reshape(-1)[i])
                    labels_to_explain = (target,)
                else:
                    labels_to_explain = (1,)
            else:
                labels_to_explain = labels

            explanation = self.explainer.explain_instance(
                data_row=row,
                predict_fn=predict_fn,
                labels=labels_to_explain,
                top_labels=top_labels,
                num_features=num_features,
                num_samples=num_samples,
                distance_metric=distance_metric,
                model_regressor=model_regressor
            )

            if top_labels is not None:
                label_to_use = explanation.top_labels[0]
            else:
                label_to_use = labels_to_explain[0] # type: ignore

            weights = np.zeros(len(self.cols), dtype=float)

            for feature_idx, weight in explanation.as_map()[label_to_use]:
                weights[int(feature_idx)] = float(weight)

            attributions.append(weights)

        return np.asarray(attributions)