# xai_metrics/base/base_explainer.py
from dataclasses import dataclass
import numpy as np
import pandas as pd
from torch.nn import Module

from typing import Mapping, Any
from xai_metrics.base.types import ExplainFunc

@dataclass(frozen=True)
class ExplainerContext:
    X_background: pd.DataFrame
    y_background: pd.Series | None = None
    model: Any | None = None
    X_batch: pd.DataFrame | None = None
    y_batch: pd.Series | None = None
    device: str | None = None


class BaseExplainer:
    """
    Base class for explanation methods.

    Subclasses must implement :meth:`explain`, which generates attribution
    values for a batch of inputs. Instances are callable and can also expose
    their explanation method as an :class:`ExplainFunc` compatible with metrics
    that need to recompute explanations.
    """
    NAME: str = "explainer"

    def __init__(
        self,
        context: ExplainerContext,
        params: Mapping[str, Any] | None = None
    ):
        """
        Parameters
        ----------
        params : Mapping[str, Any] or None, optional
            Configuration parameters used by the explanation method. A copy of
            the mapping is stored in :attr:`params`. If ``None``, an empty
            dictionary is used.
        """
        self.context = context
        self.params = dict(params or {})


    def explain(
        self,
        model: Module,
        inputs: Any,
        targets: Any | None = None,
        **kwargs: Any
    ) -> np.ndarray:
        """
        Generate explanations for the provided inputs.
        
        Subclasses must override this method with the logic required by
        the corresponding explanation method.
        
        Parameters
        ----------
        model : torch.nn.Module
            Model whose predictions are to be explained.
        inputs : Any
            Input observation or batch of observations to explain.
        targets : Any or None, optional
            Target outputs, classes or labels for which explanations are generated. Their interpretation depends on the explainer.
        **kwargs : Any
            Additional arguments required by the concrete explanation method.
        
        Returns
        -------
        numpy.ndarray
            Attribution values generated for the provided inputs.
            
        Raises
        ------
        NotImplementedError
            Always raised by the base implementation. Subclasses must override this method.
        """
        raise NotImplementedError("This class does not implement a explain method")
    
    def __call__(
        self,
        model: Module,
        inputs: Any,
        targets: Any | None = None,
        **kwargs: Any
    ) -> np.ndarray:
        """
        Generate explanations using the callable interface.

        This method delegates the computation to :meth:`explain`.

        Parameters
        ----------
        model : torch.nn.Module
            Model whose predictions are to be explained.
        inputs : Any
            Input observation or batch of observations to explain.
        targets : Any or None, optional
            Target outputs, classes or labels for which explanations are
            generated.
        **kwargs : Any
            Additional arguments forwarded to :meth:`explain`.

        Returns
        -------
        numpy.ndarray
            Attribution values generated by :meth:`explain`.
        """
        return self.explain(model=model, inputs=inputs, targets=targets, **kwargs)
    
    def as_explain_func(self) -> ExplainFunc:
        """
        Return the explanation method as a metric-compatible function.

        The returned bound method can be passed as an ``explain_func``
        dependency to metrics that need to generate explanations for modified
        or perturbed inputs.

        Returns
        -------
        ExplainFunc
            Bound :meth:`explain` method of the current explainer instance.
        """
        return self.explain