context:
  # dataset_name: "hydraulic"
  # model_name: "IForest"
  # xai_method_name: "LIME"

  # model_path: "/Users/i12alrum/Documents/Repo/XAI_metrics/prueba/results/models/hydraulic/IForest/hydraulic_IForest_seed_0.pkl"
  # X_test_path: "/Users/i12alrum/Documents/Repo/XAI_metrics/prueba/data/hydraulic/X_test_train_norm.csv"
  # y_test_path: "/Users/i12alrum/Documents/Repo/XAI_metrics/prueba/data/hydraulic/y_test_train.csv"
  # attributions_path: "/Users/i12alrum/Documents/Repo/XAI_metrics/prueba/results/attributions/hydraulic/IForest/LIME/hydraulic_IForest_lime_attributions.csv"

  device: "cuda"
  datasets_dir: "prueba/data"
  models_dir: "prueba/results/models"
  attributions_dir: "prueba/results/attributions"

metrics:
  - name: Complexity
    params:
      normalise: true

  - name: Sparseness
    params:
      normalise: true

  - name: Consistency
    params:
      abs: true
      normalise: true

  - name: FaithfulnessEstimate
    params:
      features_in_step: 1
      abs: false
      normalise: true
      perturb_baseline: mean

  - name: Faithfulness
    params:
      base_strategy: mean

  - name: MonotonicityCorrelation
    params:
      eps: 1e-5
      nr_samples: 100
      features_in_step: 1
      abs: true
      normalise: true
      perturb_baseline: mean

  - name: MonotonicityMetric
    params:
      base_strategy: mean

  - name: Monotonicity
    params:
      features_in_step: 1
      abs: true
      normalise: true
      perturb_baseline: black

  # - name: PGU
  #   params:
  #     Type: Local
  #     k: 0.25
  #     AUC: true
  #     str: 0.1
  #     n_samples: 100
  #     seed: -1
  #     n_jobs: -1

  # - name: PGI
  #   params:
  #     Type: Local
  #     k: 0.25
  #     AUC: true
  #     str: 0.1
  #     n_samples: 100
  #     seed: -1
  #     n_jobs: -1

  - name: SensitivityN
    params:
      n_max_percentage: 1.0
      features_in_step: 1
      abs: false
      normalise: true
      perturb_baseline: uniform

  - name: Sufficiency
    params:
      threshold: 0.6
      distance_func: seuclidean
      abs: true
      normalise: true

  - name: Completeness
    params:
      abs: false
      normalise: true

  - name: NonSensitivity
    params:
      eps: 1e-5
      features_in_step: 1
      abs: true
      normalise: true
      perturb_baseline: black

  - name: LocalLipschitzEstimate
    params:
      nr_samples: 200
      abs: false
      normalise: true
      perturb_mean: 0.0
      perturb_std: 0.1

  - name: MaxSensitivity
    params:
      nr_samples: 200
      abs: false
      normalise: false
      lower_bound: 0.2

  - name: RelativeInputStability
    params:
      nr_samples: 200
      abs: false
      normalise: false

  - name: RelativeOutputStability
    params:
      nr_samples: 200
      abs: false
      normalise: false

  - name: AvgSensitivity
    params:
      nr_samples: 200
      abs: false
      normalise: false
      lower_bound: 0.2

  # - name: MuFidelity
  #   params:
  #     Type: Global
  #     one_hot_targets: true
  #     num_classes: 2
  #     batch_size: 64
  #     grid_size: 7
  #     nb_samples: 100
  #     subset_percent: 0.2

  # - name: Deletion
  #   params:
  #     Type: Global
  #     one_hot_targets: true
  #     num_classes: 2
  #     batch_size: 64
  #     grid_size: 7
  #     nb_samples: 100
  #     subset_percent: 0.2
